ARG AARCH=amd64
ARG IMAGE=ubuntu:22.04

FROM --platform=linux/${AARCH} ${IMAGE} as ros2_humble-base

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble
ENV ROS_VERSION=2
ENV ROS_PYTHON_VERSION=3
ENV ROS_LOCALHOST_ONLY=0
ENV ROS_DOMAIN_ID=0

RUN apt-get update && apt-get install -y locales apt-utils \
    && locale-gen en_US.UTF-8 \
    && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Install base packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    lsb-release \
    gnupg2 \
    libc6-dev \
    x11-apps \
    software-properties-common && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set up ROS 2 repository
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu \
    $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
    > /etc/apt/sources.list.d/ros2.list

# Install ROS 2 and development tools
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    ros-humble-desktop \
    ros-dev-tools \
    ros-humble-ament-cmake \
    python3-dev \
    python3-pip \
    ninja-build \
    python3-rosdep \
    python3-colcon-common-extensions \
    python3-colcon-ros \
    clang-format && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip3 install --no-cache-dir \
    pyserial \
    adafruit-circuitpython-lis3dh \
    adafruit-circuitpython-pca9685 \
    adafruit-circuitpython-motorkit \
    Adafruit-Blinka \
    adafruit-circuitpython-bme280 \
    adafruit-circuitpython-ens160 \
    adafruit-circuitpython-busdevice \
    adafruit-circuitpython-register \
    pyubx2 \
    black \
    RPi.GPIO \
    rpi-hardware-pwm


FROM ros2_humble-base as rosdeps
# Set project directory
ARG DIR=/cprt_rover_24
WORKDIR ${DIR}

# Copy workspace into container
COPY . ${DIR}

# Generate list of rosdep dependencies to be installed later
RUN apt-get update && \
    rosdep init && \
    rosdep update && \
    rosdep install -i -r -y --from-paths src -s > /opt/rosdeps.sh

RUN ldconfig

FROM ros2_humble-base as dev
COPY --from=rosdeps /opt/rosdeps.sh /opt/rosdeps.sh

# Install rosdep dependencies
RUN apt-get update && \
    chmod +x /opt/rosdeps.sh && \
    /opt/rosdeps.sh && \
    rm -rf /var/lib/apt/lists/*

# Create entrypoint script
RUN echo '#!/bin/bash' > /entrypoint.sh && \
    echo 'source /opt/ros/humble/setup.bash' >> /entrypoint.sh && \
    echo 'if [ -f /cprt_rover_24/install/setup.bash ]; then source /cprt_rover_24/install/setup.bash; fi' >> /entrypoint.sh && \
    echo 'exec "$@"' >> /entrypoint.sh && \
    chmod +x /entrypoint.sh

RUN useradd -ms /bin/bash -u 1000 vscode \
    && echo "vscode ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Set entrypoint
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
