ARG IMAGE
FROM ${IMAGE} as ros2_humble-base

FROM ros2_humble-base as ros2_humble-dev

RUN apt-get update && apt-get install -y locales apt-utils \
    && locale-gen en_US.UTF-8 \
    && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Install base packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    lsb-release \
    gnupg2 \
    libc6-dev \
    x11-apps \
    software-properties-common && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install ROS 2 and development tools
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    ros-humble-desktop \
    ros-dev-tools \
    ros-humble-ament-cmake \
    python3-dev \
    python3-pip \
    ninja-build \
    python3-rosdep \
    python3-colcon-common-extensions \
    python3-colcon-ros \
    clang-format && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

FROM ros2_humble-dev as final

# Create entrypoint script
RUN echo '#!/bin/bash' > /entrypoint.sh && \
    echo 'source /opt/ros/humble/setup.bash' >> /entrypoint.sh && \
    echo 'if [ -f /cprt_rover_24/install/setup.bash ]; then source /cprt_rover_24/install/setup.bash; fi' >> /entrypoint.sh && \
    echo 'exec "$@"' >> /entrypoint.sh && \
    chmod +x /entrypoint.sh

RUN useradd -ms /bin/bash -u 1000 vscode \
    && echo "vscode ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Set entrypoint
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
