node_manager:
  ros__parameters:
    launch_keys:
    # Add the internal names for nodes here, in one list.
    - "drive"
    # Add a definition for each internal name below, similar to this.
    drive:
      display_name: "Drive"
      package: "drive"
      launch_file: "talon.launch.py"
