usb_controller:
  port0:
    min: 500
    max: 2500
  port1:
    min: 0
    max: 0
  port2:
    min: 0
    max: 0
  port3:
    min: 0
    max: 0
  port4:
    min: 0
    max: 0
  port5:
    min: 0
    max: 0
  port6:
    min: 0
    max: 0
  port7:
    min: 0
    max: 0
  port8:
    min: 0
    max: 0
  port9:
    min: 0
    max: 0
  port10:
    min: 0
    max: 0
  port11:
    min: 0
    max: 0
  port12:
    min: 0
    max: 0