USB_Servo_node:
  ros__parameters:
    servos_used: 3
    serial_port: "/dev/serial/by-id/usb-Pololu_Corporation_Pololu_Mini_Maestro_12-Channel_USB_Servo_Controller_00460938-if00"
    # Tilt
    servo0:
      name: "tilt"
      min: 350.0
      max: 2500.0
      rom: 360
    # PAN
    servo1:
      name: "pan"
      min: 350.0
      max: 2500.0
      rom: 360
    # GRIPPER
    servo3:
      name: "gripper"
      min: 500.0
      max: 2500.0
      rom: 180