name: Docker CI/CD Multi-Arch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cprtsoftware/rover

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build amd64 image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --build-arg TARGETARCH=amd64 \
            -t $IMAGE_NAME:amd64 \
            -t $IMAGE_NAME:${{ github.sha }}-amd64 \
            --load \
            .

      - name: Build arm64 image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg TARGETARCH=arm64 \
            -t $IMAGE_NAME:arm64 \
            -t $IMAGE_NAME:${{ github.sha }}-arm64 \
            --load \
            .

      - name: Create multi-arch manifest for latest
        run: |
          docker manifest create $IMAGE_NAME:latest \
            $IMAGE_NAME:amd64 \
            $IMAGE_NAME:arm64
          docker manifest push $IMAGE_NAME:latest

      - name: Create multi-arch manifest for commit SHA
        run: |
          docker manifest create $IMAGE_NAME:${{ github.sha }} \
            $IMAGE_NAME:${{ github.sha }}-amd64 \
            $IMAGE_NAME:${{ github.sha }}-arm64
          docker manifest push $IMAGE_NAME:${{ github.sha }}
